#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Writes core/f3d/src/design/unicode.rs: Python's str.isprintable() and
str.isalnum() as code point range tables.

The design stream decoder (core/f3d/src/design) reproduces the reference
decoder (a Python implementation of the format study, not part of this
repository), which filters candidate strings with these Python predicates.
Run with the Python that produced the reference JSON (its Unicode version
is written into the file):

    python3 gen_unicode_tables.py > ../src/design/unicode.rs
"""
import sys
import unicodedata


def ranges(pred):
    out = []
    start = None
    for c in range(0x110000):
        if pred(c):
            if start is None:
                start = c
        elif start is not None:
            out.append((start, c - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def table(name, doc, rs):
    lines = ["/// %s" % doc, "pub(crate) const %s: &[(u32, u32)] = &[" % name]
    row = []
    for a, b in rs:
        row.append("(0x%X, 0x%X)," % (a, b))
        if len(row) == 6:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("];")
    return "\n".join(lines)


def main():
    # Surrogates never reach the tables (strings are valid UTF-16 or rejected).
    not_printable = ranges(lambda c: not chr(c).isprintable() and not 0xD800 <= c <= 0xDFFF)
    alnum = ranges(lambda c: chr(c).isalnum())
    out = [
        "// SPDX-License-Identifier: MIT",
        "//! Character classes of Python's `str.isprintable()` and `str.isalnum()`.",
        "//!",
        "//! Generated by `core/f3d/tools/gen_unicode_tables.py` with Python %s"
        % sys.version.split()[0],
        "//! (Unicode %s); do not edit by hand. The reference decoder" % unicodedata.unidata_version,
        "//! (Python, not in this repository) filters candidate strings with these",
        "//! predicates, and the Rust decoder reproduces its choices exactly.",
        "",
        table("NOT_PRINTABLE", "Code points for which `isprintable()` is false (sorted, inclusive).",
              not_printable),
        "",
        table("ALNUM", "Code points for which `isalnum()` is true (sorted, inclusive).", alnum),
        "",
        "fn in_table(table: &[(u32, u32)], c: char) -> bool {",
        "    let c = c as u32;",
        "    table",
        "        .binary_search_by(|&(lo, hi)| {",
        "            if hi < c {",
        "                std::cmp::Ordering::Less",
        "            } else if lo > c {",
        "                std::cmp::Ordering::Greater",
        "            } else {",
        "                std::cmp::Ordering::Equal",
        "            }",
        "        })",
        "        .is_ok()",
        "}",
        "",
        "/// Python's `str.isprintable()` for one character.",
        "pub(crate) fn is_printable_char(c: char) -> bool {",
        "    !in_table(NOT_PRINTABLE, c)",
        "}",
        "",
        "/// Python's `str.isprintable()` (true for the empty string).",
        "pub(crate) fn is_printable(s: &str) -> bool {",
        "    s.chars().all(is_printable_char)",
        "}",
        "",
        "/// Python's `str.isalnum()` for one character.",
        "pub(crate) fn is_alnum_char(c: char) -> bool {",
        "    in_table(ALNUM, c)",
        "}",
        "",
    ]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
