# SPDX-License-Identifier: MIT
# Writes a C++ source that holds the bytes of files (cmake -P):
#   -DOUTPUT=<source.cpp> -DNAMESPACE=<a::b> -DNAMES=<n1>,<n2> -DPATHS=<p1>,<p2>
# Each file becomes `extern const unsigned char <name>[]` and
# `extern const std::size_t <name>_size` in the namespace.
cmake_minimum_required(VERSION 3.24)

string(REPLACE "," ";" names "${NAMES}")
string(REPLACE "," ";" paths "${PATHS}")
set(content "// Generated by geometry/cmake/embed.cmake from ${NAMES}; do not edit.\n")
string(APPEND content "#include <cstddef>\n\nnamespace ${NAMESPACE} {\n")
# 24 bytes a line.
string(REPEAT "0x[0-9a-f][0-9a-f]," 24 row)
foreach(name path IN ZIP_LISTS names paths)
  file(READ "${path}" hex HEX)
  file(SIZE "${path}" size)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(REGEX REPLACE "(${row})" "\\1\n" bytes "${bytes}")
  string(APPEND content "\nextern const unsigned char ${name}[${size}];\n")
  string(APPEND content "const unsigned char ${name}[${size}] = {\n${bytes}\n};\n")
  string(APPEND content "extern const std::size_t ${name}_size;\n")
  string(APPEND content "const std::size_t ${name}_size = ${size};\n")
endforeach()
string(APPEND content "\n} // namespace ${NAMESPACE}\n")
file(WRITE "${OUTPUT}" "${content}")
