// SPDX-License-Identifier: MIT
#include "mitcad/geometry/faceops.hpp"

#include <algorithm>
#include <cmath>
#include <map>
#include <set>
#include <stdexcept>

#include <BOPAlgo_Alerts.hxx>
#include <BRepAlgoAPI_Defeaturing.hxx>
#include <BRepAlgoAPI_Fuse.hxx>
#include <BRepAdaptor_Surface.hxx>
#include <BRepAlgoAPI_Splitter.hxx>
#include <BRepGProp.hxx>
#include <BRepOffsetAPI_DraftAngle.hxx>
#include <BRepOffsetAPI_MakeOffsetShape.hxx>
#include <BRepOffsetAPI_MakeThickSolid.hxx>
#include <BRepOffset_MakeOffset.hxx>
#include <BRepTools.hxx>
#include <BRep_Builder.hxx>
#include <BRep_Tool.hxx>
#include <GProp_GProps.hxx>
#include <GeomAPI_ProjectPointOnSurf.hxx>
#include <Geom_Surface.hxx>
#include <NCollection_List.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Shell.hxx>
#include <TopoDS_Solid.hxx>

#include "face_select.hpp"
#include "history.hpp"
#include "mitcad/geometry/split.hpp"
#include "replace.hpp"
#include "util.hpp"

namespace mitcad::geometry {
namespace {

constexpr double kTolerance = 1.0e-6;
constexpr double kHalfPi = 1.57079632679489661923;

void require_not_negative(const char* what, double value) {
  if (!(value >= 0.0) || !std::isfinite(value)) {
    throw std::invalid_argument(std::string(what) + " must not be negative");
  }
}

// The faces of the result that an input face became: its modified images,
// or itself when it is kept unchanged.
template <class Operation>
std::vector<TopoDS_Shape> images_of(Operation& operation, const TopoDS_Shape& face,
                                    const TopoDS_Shape& result) {
  std::vector<TopoDS_Shape> images;
  if (operation.IsDeleted(face)) {
    return images;
  }
  for (const TopoDS_Shape& image : operation.Modified(face)) {
    if (image.ShapeType() == TopAbs_FACE) {
      images.push_back(image);
    }
  }
  if (images.empty()) {
    ShapeMap faces;
    TopExp::MapShapes(result, TopAbs_FACE, faces);
    if (faces.Contains(face)) {
      images.push_back(face);
    }
  }
  return images;
}

template <class Operation>
std::vector<TopoDS_Shape> generated_faces(Operation& operation, const TopoDS_Shape& source) {
  std::vector<TopoDS_Shape> faces;
  for (const TopoDS_Shape& image : operation.Generated(source)) {
    if (image.ShapeType() == TopAbs_FACE) {
      faces.push_back(image);
    }
  }
  return faces;
}

void add_names(detail::FaceNamer& namer, const TopoDS_Shape& face, const NameList& names) {
  for (const std::string& name : names) {
    namer.add(face, name);
  }
}

// True when the face lies on the surface of the reference face.
bool on_surface(const TopoDS_Face& face, const TopoDS_Face& reference) {
  double u1 = 0, u2 = 0, v1 = 0, v2 = 0;
  BRepTools::UVBounds(face, u1, u2, v1, v2);
  const BRepAdaptor_Surface surface(face, false);
  const occ::handle<Geom_Surface> target = BRep_Tool::Surface(reference);
  for (const double s : {0.5, 0.3}) {
    const gp_Pnt p = surface.Value(u1 + (u2 - u1) * s, v1 + (v2 - v1) * (1 - s));
    GeomAPI_ProjectPointOnSurf projection(p, target);
    if (projection.NbPoints() == 0 || projection.LowerDistance() > 1.0e-6) {
      return false;
    }
  }
  return true;
}

// Runs an OCCT step, naming it in the error OCCT may raise without a message.
template <class Step>
auto step(const std::string& what, Step&& run) -> decltype(run()) {
  try {
    return run();
  } catch (const Standard_Failure& failure) {
    const std::string message = failure.what();
    throw std::runtime_error(what + (message.empty() ? "" : ": " + message));
  }
}

// One solid of an offset or thick solid result; throws if there is none.
TopoDS_Shape single_solid(const TopoDS_Shape& shape, const char* operation) {
  TopExp_Explorer it(shape, TopAbs_SOLID);
  if (!it.More()) {
    throw std::runtime_error(std::string(operation) + " produced no solid");
  }
  const TopoDS_Shape solid = it.Current();
  it.Next();
  if (it.More()) {
    throw std::runtime_error(std::string(operation) + " produced several solids");
  }
  return solid;
}

// Names the faces generated by an offset or thick solid from the body's
// edges and vertices (wall ends at removed faces, rounded joins) when they
// have no name yet.
template <class Operation>
void name_generated_from_edges(detail::FaceNamer& namer, Operation& operation, const Shape& body,
                               const std::string& feature, const std::set<int>& removed) {
  for (int e = 0; e < body.edge_count(); ++e) {
    const std::string& name = body.edge_name(e);
    if (name.empty()) {
      continue;
    }
    bool at_removed = false;
    for (int f : detail::faces_at_edge(body, e)) {
      at_removed = at_removed || removed.count(f) > 0;
    }
    for (const TopoDS_Shape& face : generated_faces(operation, body.edge(e))) {
      if (!namer.named(face)) {
        namer.add(face, face_name(feature, at_removed ? "offset_cap" : "offset", name));
      }
    }
  }
  for (int v = 0; v < body.vertex_count(); ++v) {
    const std::string& name = body.vertex_name(v);
    if (name.empty()) {
      continue;
    }
    for (const TopoDS_Shape& face : generated_faces(operation, body.vertex(v))) {
      if (!namer.named(face)) {
        namer.add(face, face_name(feature, "offset", name));
      }
    }
  }
}

// The wall between the body's surface and its offset by `offset` (negative
// inside), with the removed faces open. The outside of the wall keeps the
// face names; the inside is offset(<face>).
ShapePtr thick_solid(const std::string& feature, const Shape& input, const std::set<int>& removed,
                     double offset, GeomAbs_JoinType join) {
  // OCCT's offset widens the tolerances of its input's sub-shapes.
  const ShapePtr copy = detail::working_copy(input);
  const Shape& body = *copy;
  NCollection_List<TopoDS_Shape> closing;
  for (int f : removed) {
    closing.Append(body.face(f));
  }
  BRepOffsetAPI_MakeThickSolid maker;
  detail::interruptible([&](const Message_ProgressRange& range) {
    maker.MakeThickSolidByJoin(body.occt(), closing, offset, kTolerance, BRepOffset_Skin, false, false,
                               join, false, range);
  });
  if (!maker.IsDone()) {
    throw std::runtime_error("shell failed; the thickness may be too large for the body");
  }
  const TopoDS_Shape result = single_solid(maker.Shape(), "the shell");
  detail::FaceNamer namer(result);
  for (int i = 0; i < body.face_count(); ++i) {
    if (removed.count(i) > 0) {
      continue;
    }
    const NameList& names = body.face_names(i);
    const std::string inner = face_name(feature, "offset", detail::primary_name(body, i));
    const bool unnamed = names.empty();
    for (const TopoDS_Shape& face : images_of(maker, body.face(i), result)) {
      if (offset < 0) {
        add_names(namer, face, names);
      } else if (!unnamed) {
        namer.add(face, inner);
      }
    }
    for (const TopoDS_Shape& face : generated_faces(maker, body.face(i))) {
      if (offset > 0) {
        add_names(namer, face, names);
      } else if (!unnamed) {
        namer.add(face, inner);
      }
    }
  }
  name_generated_from_edges(namer, maker, body, feature, removed);
  // The end of the wall where a removed face was: generated from it, or
  // else lying on its surface.
  for (int f : removed) {
    const std::string name = face_name(feature, "offset_cap", detail::primary_name(body, f));
    if (detail::primary_name(body, f).empty()) {
      continue;
    }
    std::vector<TopoDS_Shape> caps = generated_faces(maker, body.face(f));
    for (const TopoDS_Shape& image : maker.Modified(body.face(f))) {
      caps.push_back(image);
    }
    for (TopExp_Explorer it(result, TopAbs_FACE); it.More(); it.Next()) {
      if (!namer.named(it.Current()) && on_surface(TopoDS::Face(it.Current()), body.face(f))) {
        caps.push_back(it.Current());
      }
    }
    for (const TopoDS_Shape& cap : caps) {
      if (cap.ShapeType() == TopAbs_FACE && !namer.named(cap)) {
        namer.add(cap, name);
      }
    }
  }
  namer.finish();
  return namer.shape();
}

// The body offset by `offset` as a closed solid, with each face named after
// the body face it comes from: the same names, or offset(<face>) with `inner`.
ShapePtr offset_body(const std::string& feature, const Shape& input, double offset,
                     GeomAbs_JoinType join, bool inner) {
  // OCCT's offset widens the tolerances of its input's sub-shapes.
  const ShapePtr copy = detail::working_copy(input);
  const Shape& body = *copy;
  BRepOffsetAPI_MakeOffsetShape maker;
  detail::interruptible([&](const Message_ProgressRange& range) {
    maker.PerformByJoin(body.occt(), offset, kTolerance, BRepOffset_Skin, false, false, join, false, range);
  });
  if (!maker.IsDone()) {
    throw std::runtime_error("shell failed; the thickness may be too large for the body");
  }
  const TopoDS_Shape result = single_solid(maker.Shape(), "the shell");
  detail::FaceNamer namer(result);
  for (int i = 0; i < body.face_count(); ++i) {
    const NameList& names = body.face_names(i);
    if (names.empty()) {
      continue;
    }
    for (const TopoDS_Shape& face : generated_faces(maker, body.face(i))) {
      if (inner) {
        namer.add(face, face_name(feature, "offset", names.front()));
      } else {
        add_names(namer, face, names);
      }
    }
  }
  name_generated_from_edges(namer, maker, body, feature, {});
  return namer.shape();
}

// The body itself with every face renamed offset(<face>), as a void.
ShapePtr renamed_as_inner(const std::string& feature, const Shape& body) {
  std::vector<Shape::NamedFace> faces;
  for (int i = 0; i < body.face_count(); ++i) {
    if (!body.face_names(i).empty()) {
      faces.push_back({body.face(i), {face_name(feature, "offset", body.face_names(i).front())}});
    }
  }
  return std::make_shared<Shape>(body.occt(), faces);
}

TopoDS_Shell outer_shell(const TopoDS_Shape& solid) {
  TopExp_Explorer it(solid, TopAbs_SHELL);
  if (!it.More()) {
    throw std::runtime_error("the shell has no surface");
  }
  return TopoDS::Shell(it.Current());
}

// A solid bounded by the outer body and, reversed, the inner one.
ShapePtr hollow(const Shape& outer, const Shape& inner) {
  BRep_Builder builder;
  TopoDS_Solid solid;
  builder.MakeSolid(solid);
  builder.Add(solid, outer_shell(outer.occt()));
  builder.Add(solid, outer_shell(inner.occt()).Reversed());
  std::vector<Shape::NamedFace> faces;
  for (const Shape* part : {&outer, &inner}) {
    for (int i = 0; i < part->face_count(); ++i) {
      faces.push_back({part->face(i), part->face_names(i)});
    }
  }
  detail::FaceNamer namer(solid);
  for (const Shape::NamedFace& face : faces) {
    add_names(namer, face.face, face.names);
  }
  namer.finish();
  return namer.shape();
}

// Fuses the inner and outer walls of a shell to both sides.
ShapePtr fuse_walls(const Shape& inner, const Shape& outer) {
  BRepAlgoAPI_Fuse fuse;
  NCollection_List<TopoDS_Shape> arguments;
  arguments.Append(inner.occt());
  NCollection_List<TopoDS_Shape> tools;
  tools.Append(outer.occt());
  fuse.SetArguments(arguments);
  fuse.SetTools(tools);
  fuse.SetNonDestructive(true);
  detail::build(fuse);
  if (!fuse.IsDone() || fuse.HasErrors()) {
    throw std::runtime_error("shell failed; the inner and outer walls could not be joined");
  }
  fuse.SimplifyResult();
  detail::FaceNamer namer(fuse.Shape());
  namer.carry(fuse, inner);
  namer.carry(fuse, outer);
  namer.finish();
  return namer.shape();
}

void check_result(const ShapePtr& shape, const char* operation) {
  detail::require_valid(shape->occt(), operation);
  GProp_GProps props;
  BRepGProp::VolumeProperties(shape->occt(), props);
  if (!(props.Mass() > kTolerance)) {
    throw std::runtime_error(std::string(operation) + " produced an empty body");
  }
}

std::set<int> as_set(const std::vector<int>& faces) { return {faces.begin(), faces.end()}; }

} // namespace

ShapePtr shell(const std::string& feature, const Shape& body, const ShellSpec& spec) {
  require_not_negative("the inside thickness", spec.inside);
  require_not_negative("the outside thickness", spec.outside);
  if (spec.inside == 0.0 && spec.outside == 0.0) {
    throw std::invalid_argument("the shell needs an inside or an outside thickness");
  }
  std::vector<int> faces;
  if (!spec.faces.empty()) {
    faces = detail::resolve_faces(body, spec.faces, "faces to remove");
    if (spec.tangent_chain) {
      faces = detail::tangent_closure(body, faces);
    }
    if (static_cast<int>(faces.size()) >= body.face_count()) {
      throw std::invalid_argument("the shell cannot remove every face of the body");
    }
  }
  const GeomAbs_JoinType join = spec.rounded ? GeomAbs_Arc : GeomAbs_Intersection;
  return detail::run("shell", [&] {
    ShapePtr result;
    if (faces.empty()) {
      const ShapePtr outer = spec.outside > 0.0
                                 ? offset_body(feature, body, spec.outside, join, false)
                                 : std::make_shared<Shape>(body);
      const ShapePtr inner = spec.inside > 0.0 ? offset_body(feature, body, -spec.inside, join, true)
                                               : renamed_as_inner(feature, body);
      result = hollow(*outer, *inner);
    } else {
      const std::set<int> removed = as_set(faces);
      if (spec.outside == 0.0) {
        result = thick_solid(feature, body, removed, -spec.inside, join);
      } else if (spec.inside == 0.0) {
        result = thick_solid(feature, body, removed, spec.outside, join);
      } else {
        result = fuse_walls(*thick_solid(feature, body, removed, -spec.inside, join),
                            *thick_solid(feature, body, removed, spec.outside, join));
      }
    }
    check_result(result, "the shell");
    return result;
  });
}

namespace {

// Drafts the faces of the body about the neutral plane in the pull direction.
ShapePtr draft_faces(const Shape& body, const std::vector<int>& faces, const gp_Pln& neutral,
                     const gp_Dir& pull, double angle, bool tangent_chain) {
  BRepOffsetAPI_DraftAngle maker(body.occt());
  const std::set<int> selected(faces.begin(), faces.end());
  // The faces drafted so far, the tangent ones OCCT adds included.
  std::set<int> drafted;
  for (int f : faces) {
    if (drafted.count(f) > 0) {
      continue;
    }
    const TopoDS_Face& face = body.face(f);
    step("draft failed on face " + detail::primary_name(body, f),
         [&] { maker.Add(face, pull, angle, neutral, true); });
    if (!maker.AddDone()) {
      throw std::runtime_error("draft failed on face " + detail::primary_name(body, f) +
                               "; only planar, cylindrical and conical faces can be drafted, "
                               "and the fixed plane must cross them");
    }
    // OCCT drafts the tangent neighbours along.
    for (int index : detail::tangent_closure(body, {f})) {
      drafted.insert(index);
      if (!tangent_chain && selected.count(index) == 0) {
        throw std::invalid_argument(
            "unsupported: face " + detail::primary_name(body, index) +
            " is tangent to a drafted face; without a tangent chain only the selected faces "
            "would be drafted, but the geometry kernel always drafts the whole chain");
      }
    }
  }
  step("draft failed", [&] { detail::build(maker); });
  if (!maker.IsDone()) {
    throw std::runtime_error("draft failed; the neighbouring faces cannot follow the drafted faces");
  }
  // The modifier rebuilds every face it touches; ModifiedShape gives the image.
  detail::FaceNamer namer(maker.Shape());
  for (int i = 0; i < body.face_count(); ++i) {
    const TopoDS_Shape image = step("draft", [&] { return maker.ModifiedShape(body.face(i)); });
    add_names(namer, image, body.face_names(i));
  }
  namer.finish();
  return namer.shape();
}

// The faces of the shape the references resolve to, if any.
std::vector<int> faces_in(const Shape& shape, const std::vector<std::string>& references) {
  std::vector<int> faces;
  for (const std::string& reference : references) {
    for (int f : shape.find_faces(reference)) {
      if (std::find(faces.begin(), faces.end(), f) == faces.end()) {
        faces.push_back(f);
      }
    }
  }
  return faces;
}

// Merges the pieces a split left of a name of the original body back into
// the name where one face holds them all again ("X#0", "X#1" -> "X").
ShapePtr join_pieces(const Shape& shape, const Shape& original) {
  std::set<std::string> before;
  for (int i = 0; i < original.face_count(); ++i) {
    before.insert(original.face_names(i).begin(), original.face_names(i).end());
  }
  // The name a piece name comes from, or empty.
  const auto base = [&before](const std::string& name) {
    const std::size_t mark = name.rfind('#');
    if (mark == std::string::npos || name.find_first_of(")]}", mark) != std::string::npos ||
        before.count(name.substr(0, mark)) == 0) {
      return std::string();
    }
    return name.substr(0, mark);
  };
  std::map<std::string, std::vector<int>> holders; // base name -> faces holding a piece
  for (int i = 0; i < shape.face_count(); ++i) {
    for (const std::string& name : shape.face_names(i)) {
      if (!base(name).empty()) {
        holders[base(name)].push_back(i);
      }
    }
  }
  detail::FaceNamer namer(shape.occt());
  for (int i = 0; i < shape.face_count(); ++i) {
    for (const std::string& name : shape.face_names(i)) {
      const std::size_t mark = name.rfind('#');
      std::string kept = name;
      if (!base(name).empty()) {
        const std::vector<int>& faces = holders[name.substr(0, mark)];
        if (std::all_of(faces.begin(), faces.end(), [i](int f) { return f == i; })) {
          kept = name.substr(0, mark);
        }
      }
      namer.add(shape.face(i), kept);
    }
  }
  namer.finish();
  return namer.shape();
}

} // namespace

ShapePtr draft(const std::string& feature, const Shape& body, const DraftSpec& spec) {
  for (const std::optional<double> angle : {std::optional<double>(spec.angle), spec.angle2}) {
    if (angle && !(std::abs(*angle) < kHalfPi && *angle != 0.0)) {
      throw std::invalid_argument("the draft angle must be between -90 and 90 degrees and not zero");
    }
  }
  if (spec.plane.kind != Tool::Kind::Plane && spec.plane.kind != Tool::Kind::Face) {
    throw std::invalid_argument("the fixed plane must be a plane or a planar face");
  }
  const gp_Pln neutral = detail::tool_plane(spec.plane, "the fixed plane");
  gp_Dir pull = neutral.Axis().Direction();
  if (spec.plane.kind == Tool::Kind::Face) {
    // From the face into the material.
    pull.Reverse();
  }
  if (spec.flip) {
    pull.Reverse();
  }
  const std::vector<int> faces = detail::resolve_faces(body, spec.faces, "faces to draft");
  return detail::run("draft", [&] {
    ShapePtr result;
    if (!spec.angle2) {
      result = draft_faces(body, faces, neutral, pull, spec.angle, spec.tangent_chain);
    } else {
      // Each side of the plane tilts on its own: split the body there, draft
      // the halves (so that OCCT does not carry a draft across the split
      // into the coplanar other half) and join them again.
      const std::vector<ShapePtr> halves =
          split_body(feature, body, Tool::of_plane(neutral), true);
      std::vector<ShapePtr> drafted;
      for (const ShapePtr& half : halves) {
        GProp_GProps props;
        BRepGProp::VolumeProperties(half->occt(), props);
        const bool pull_side =
            gp_Vec(neutral.Location(), props.CentreOfMass()).Dot(gp_Vec(pull)) > 0.0;
        const std::vector<int> own = faces_in(*half, spec.faces);
        drafted.push_back(own.empty() ? half
                                      : draft_faces(*half, own, neutral,
                                                    pull_side ? pull : pull.Reversed(),
                                                    pull_side ? spec.angle : *spec.angle2,
                                                    spec.tangent_chain));
      }
      result = drafted.front();
      for (std::size_t i = 1; i < drafted.size(); ++i) {
        result = fuse_walls(*result, *drafted[i]);
      }
      result = join_pieces(*result, body);
    }
    check_result(result, "the draft");
    return result;
  });
}

namespace {

// Moves each face by its own offset; the other faces stay on their surfaces.
// `except` are faces not to carry the names of.
detail::FaceNamer move_faces(const Shape& body, const std::vector<std::pair<int, double>>& moves,
                             const std::vector<int>& except, NCollection_List<TopoDS_Shape>& moved) {
  BRepOffset_MakeOffset maker;
  maker.Initialize(body.occt(), 0.0, kTolerance, BRepOffset_Skin, false, false,
                   GeomAbs_Intersection, false, false);
  for (const auto& [face, distance] : moves) {
    maker.SetOffsetOnFace(body.face(face), distance);
  }
  detail::interruptible([&](const Message_ProgressRange& range) { maker.MakeOffsetShape(range); });
  if (!maker.IsDone()) {
    throw std::runtime_error("the neighbouring faces cannot follow the moved faces");
  }
  const TopoDS_Shape result = single_solid(maker.Shape(), "the offset");
  NCollection_List<TopoDS_Shape> arguments;
  arguments.Append(body.occt());
  const BRepTools_History history(arguments, maker);
  detail::FaceNamer namer(result);
  namer.carry(history, body, except);
  for (int i = 0; i < body.face_count(); ++i) {
    const bool skip = std::find(except.begin(), except.end(), i) != except.end();
    const bool is_moved = std::any_of(moves.begin(), moves.end(),
                                      [i](const auto& move) { return move.first == i; });
    std::vector<TopoDS_Shape> images;
    for (const TopoDS_Shape& image : history.Generated(body.face(i))) {
      if (image.ShapeType() == TopAbs_FACE) {
        images.push_back(image);
      }
    }
    for (const TopoDS_Shape& image : history.Modified(body.face(i))) {
      if (image.ShapeType() == TopAbs_FACE) {
        images.push_back(image);
      }
    }
    if (images.empty() && !history.IsRemoved(body.face(i)) && namer.contains(body.face(i))) {
      images.push_back(body.face(i));
    }
    for (const TopoDS_Shape& image : images) {
      if (is_moved) {
        moved.Append(image);
      }
      if (!skip && !namer.named(image)) {
        add_names(namer, image, body.face_names(i));
      }
    }
  }
  return namer;
}

} // namespace

ShapePtr offset_faces(const std::string& feature, const Shape& body,
                      const std::vector<std::string>& faces, double distance) {
  (void)feature;
  detail::require_finite("offset distance", distance);
  if (distance == 0.0) {
    throw std::invalid_argument("the offset distance must not be zero");
  }
  const std::vector<int> chosen = detail::resolve_faces(body, faces, "faces to offset");
  return detail::run("offset faces", [&] {
    std::vector<std::pair<int, double>> moves;
    for (int f : chosen) {
      moves.emplace_back(f, distance);
    }
    NCollection_List<TopoDS_Shape> moved;
    detail::FaceNamer namer = move_faces(body, moves, {}, moved);
    namer.finish();
    ShapePtr result = namer.shape();
    check_result(result, "the offset");
    return result;
  });
}

ShapePtr delete_faces(const std::string& feature, const Shape& body,
                      const std::vector<std::string>& faces) {
  (void)feature;
  const std::vector<int> chosen = detail::resolve_faces(body, faces, "faces to delete");
  return detail::run("delete faces", [&] {
    BRepAlgoAPI_Defeaturing maker;
    maker.SetShape(body.occt());
    for (int f : chosen) {
      maker.AddFaceToRemove(body.face(f));
    }
    maker.SetRunParallel(false);
    maker.SetToFillHistory(true);
    detail::build(maker);
    if (!maker.IsDone() || maker.HasErrors() ||
        maker.HasWarning(STANDARD_TYPE(BOPAlgo_AlertUnableToRemoveTheFeature))) {
      throw std::runtime_error(
          "the faces cannot be deleted: the neighbouring faces do not close the gap");
    }
    for (int f : chosen) {
      if (!maker.IsDeleted(body.face(f))) {
        throw std::runtime_error("face " + detail::primary_name(body, f) + " could not be deleted");
      }
    }
    detail::FaceNamer namer(maker.Shape());
    namer.carry(maker, body);
    namer.finish();
    ShapePtr result = namer.shape();
    check_result(result, "deleting faces");
    return result;
  });
}

ShapePtr replace_faces(const std::string& feature, const Shape& body,
                       const std::vector<std::string>& faces, const Tool& target,
                       bool tangent_chain) {
  if (target.kind == Tool::Kind::Curves) {
    throw std::invalid_argument("the target must be a plane, a face or a body");
  }
  std::vector<int> chosen = detail::resolve_faces(body, faces, "faces to replace");
  if (tangent_chain) {
    chosen = detail::tangent_closure(body, chosen);
  }
  // Planar faces onto a plane or a planar face move there; other faces and
  // targets take the region between them (replace.cpp).
  bool planar = target.kind != Tool::Kind::Body &&
                std::all_of(chosen.begin(), chosen.end(),
                            [&](int f) { return detail::face_plane(body.face(f)).has_value(); });
  if (planar && target.kind == Tool::Kind::Face) {
    if (!target.shape) {
      throw std::invalid_argument("the target face has no body");
    }
    const std::vector<int> found =
        detail::resolve_faces(*target.shape, {target.face}, "target faces");
    planar = detail::face_plane(target.shape->face(found.front())).has_value();
  }
  if (!planar) {
    std::string replaced;
    for (int f : chosen) {
      replaced = replaced.empty() ? detail::primary_name(body, f) : replaced;
    }
    return detail::run("replace faces", [&] {
      ShapePtr result =
          detail::replace_by_slab(body, chosen, target, face_name(feature, "replace", replaced));
      check_result(result, "replacing faces");
      return result;
    });
  }
  const gp_Pln plane = detail::tool_plane(target, "the target face");
  const gp_Dir up = plane.Axis().Direction();
  return detail::run("replace faces", [&] {
    // Move each face onto the target where it is parallel; past the target
    // where it is not, and cut back to it afterwards.
    std::vector<std::pair<int, double>> moves;
    bool tilted = false;
    for (int f : chosen) {
      const gp_Dir normal = detail::face_plane(body.face(f))->Axis().Direction();
      const double facing = normal.Dot(up);
      if (std::abs(facing) < 1.0e-3) {
        throw std::invalid_argument("the target is perpendicular to face " +
                                    detail::primary_name(body, f));
      }
      // Where the face's normal line through each vertex meets the target.
      double nearest = 0.0;
      double farthest = 0.0;
      bool first = true;
      for (TopExp_Explorer it(body.face(f), TopAbs_VERTEX); it.More(); it.Next()) {
        const gp_Pnt p = BRep_Tool::Pnt(TopoDS::Vertex(it.Current()));
        const double t = gp_Vec(p, plane.Location()).Dot(gp_Vec(up)) / facing;
        nearest = first ? t : std::min(nearest, t);
        farthest = first ? t : std::max(farthest, t);
        first = false;
      }
      if (std::abs(1.0 - std::abs(facing)) > 1.0e-9) {
        tilted = true;
        // Past the target everywhere on the face.
        moves.emplace_back(f, farthest + std::max(1.0, farthest - nearest));
      } else {
        moves.emplace_back(f, farthest);
      }
    }
    std::string replaced;
    for (int f : chosen) {
      replaced = replaced.empty() ? detail::primary_name(body, f) : replaced;
    }
    const std::string name = face_name(feature, "replace", replaced);
    NCollection_List<TopoDS_Shape> moved;
    ShapePtr result;
    const bool still = std::all_of(moves.begin(), moves.end(), [](const auto& move) {
      return std::abs(move.second) <= kTolerance;
    });
    if (still && !tilted) {
      // Already on the target: only the names change.
      std::vector<Shape::NamedFace> named;
      for (int i = 0; i < body.face_count(); ++i) {
        const bool source = std::find(chosen.begin(), chosen.end(), i) != chosen.end();
        named.push_back({body.face(i), source ? NameList{name} : body.face_names(i)});
      }
      result = std::make_shared<Shape>(body.occt(), named);
    } else if (!tilted) {
      detail::FaceNamer namer = move_faces(body, moves, chosen, moved);
      for (const TopoDS_Shape& face : moved) {
        namer.add(face, name);
      }
      namer.finish();
      result = namer.shape();
    } else {
      // Grown past the target, then split at it; the pieces past it that hold
      // a moved face go, the rest join again.
      ShapePtr grown;
      if (still) {
        // Already past the target everywhere.
        grown = std::make_shared<Shape>(body);
        for (int f : chosen) {
          moved.Append(body.face(f));
        }
      } else {
        detail::FaceNamer grown_namer = move_faces(body, moves, chosen, moved);
        grown_namer.finish();
        grown = grown_namer.shape();
      }
      const TopoDS_Face cut = detail::plane_face(plane, detail::box_of(grown->occt()));
      BRepAlgoAPI_Splitter splitter;
      NCollection_List<TopoDS_Shape> arguments;
      arguments.Append(grown->occt());
      NCollection_List<TopoDS_Shape> tools;
      tools.Append(cut);
      splitter.SetArguments(arguments);
      splitter.SetTools(tools);
      splitter.SetNonDestructive(true);
      detail::build(splitter);
      if (!splitter.IsDone() || splitter.HasErrors()) {
        throw std::runtime_error("the body could not be cut at the target");
      }
      ShapeMap moved_images;
      for (const TopoDS_Shape& face : moved) {
        for (const TopoDS_Shape& image : images_of(splitter, face, splitter.Shape())) {
          moved_images.Add(image);
        }
      }
      detail::FaceNamer split_namer(splitter.Shape());
      split_namer.carry(splitter, *grown);
      for (const TopoDS_Shape& image : splitter.Modified(cut)) {
        split_namer.add(image, name);
      }
      split_namer.finish();
      std::vector<ShapePtr> kept;
      for (TopExp_Explorer it(splitter.Shape(), TopAbs_SOLID); it.More(); it.Next()) {
        bool holds_moved = false;
        for (TopExp_Explorer f(it.Current(), TopAbs_FACE); f.More() && !holds_moved; f.Next()) {
          holds_moved = moved_images.Contains(f.Current());
        }
        if (!holds_moved) {
          std::vector<Shape::NamedFace> named;
          const ShapePtr all = split_namer.shape();
          for (TopExp_Explorer f(it.Current(), TopAbs_FACE); f.More(); f.Next()) {
            named.push_back({f.Current(), all->names_of_face(f.Current())});
          }
          kept.push_back(std::make_shared<Shape>(it.Current(), named));
        }
      }
      if (kept.empty()) {
        throw std::runtime_error("the target removes the whole body");
      }
      result = kept.front();
      for (std::size_t i = 1; i < kept.size(); ++i) {
        result = fuse_walls(*result, *kept[i]);
      }
      // The cut faces carry the name with split numbers; number them afresh.
      detail::FaceNamer renamed(result->occt());
      for (int i = 0; i < result->face_count(); ++i) {
        for (const std::string& n : result->face_names(i)) {
          renamed.add(result->face(i), name_matches(n, name) ? name : n);
        }
      }
      renamed.finish();
      result = renamed.shape();
    }
    if (result->find_faces(name).empty()) {
      throw std::runtime_error("the target does not meet the body where the faces are");
    }
    check_result(result, "replacing faces");
    return result;
  });
}

} // namespace mitcad::geometry
