# SPDX-License-Identifier: MIT
# The crates' tests in ctest (core/CMakeLists.txt, mitcad#101), in script
# mode, with the arguments after "--":
#
#   cmake -DCARGO=<cargo> -DMANIFEST=<core/Cargo.toml> -DLIST=<file> -P cargo-tests.cmake
#         -- build [--release] <package>...
#     Builds the test binaries of the packages in one cargo run (cargo test
#     --no-run) and lists them in LIST, a line per binary: the package, its
#     folder, the target and the binary, separated by tabs.
#   cmake -DLIST=<file> -P cargo-tests.cmake -- run <package> [<argument>...]
#     Runs the package's test binaries in the package's folder, as cargo
#     test does, with libtest's arguments (a filter, --skip <filter>).
#   cmake -DLIST=<file> -P cargo-tests.cmake -- parts <package> <filter>...
#     Checks the parts a package's tests run in: those of each filter, and
#     the rest (--skip of every filter). Together they must list each test
#     of the package's binaries (--list) exactly once, and each filter must
#     match a test (else it is left from a module renamed or removed).
cmake_minimum_required(VERSION 3.24)

# The arguments after "--".
set(args)
set(after FALSE)
math(EXPR last "${CMAKE_ARGC} - 1")
foreach(i RANGE ${last})
  if(after)
    list(APPEND args "${CMAKE_ARGV${i}}")
  elseif("${CMAKE_ARGV${i}}" STREQUAL "--")
    set(after TRUE)
  endif()
endforeach()
list(POP_FRONT args mode)

# package_name(<id> <out>): the name in a cargo package id, in the form
# path+file:///.../vcs#mitcad-vcs@0.2.0, path+file:///.../name#0.2.0 (the
# name is the folder's) or the older "mitcad-vcs 0.2.0 (path+file:///...)".
function(package_name id out)
  if(id MATCHES "#([^#@]+)@[^#]*$")
    set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  elseif(id MATCHES "/([^/#]+)#[^#@]*$")
    set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  elseif(id MATCHES "^([^ ]+) ")
    set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "cannot read the package id ${id}")
  endif()
endfunction()

# binaries(<package> <out>): the package's lines of LIST, each the folder,
# the target and the binary separated by "|".
function(binaries package out)
  if(NOT EXISTS "${LIST}")
    message(FATAL_ERROR "${LIST} is missing: the test binaries were not built")
  endif()
  file(READ "${LIST}" text)
  string(REPLACE "\n" ";" lines "${text}")
  set(found)
  foreach(line IN LISTS lines)
    if(line STREQUAL "")
      continue()
    endif()
    string(REPLACE "\t" ";" fields "${line}")
    list(POP_FRONT fields name)
    if(name STREQUAL package)
      list(JOIN fields "|" entry)
      list(APPEND found "${entry}")
    endif()
  endforeach()
  if(NOT found)
    message(FATAL_ERROR "no test binaries of ${package} in ${LIST}")
  endif()
  set(${out} "${found}" PARENT_SCOPE)
endfunction()

# list_tests(<binary> <folder> <out> [<argument>...]): the tests the binary
# runs with these arguments (libtest's --list).
function(list_tests binary folder out)
  execute_process(COMMAND "${binary}" --list --format terse ${ARGN} WORKING_DIRECTORY "${folder}"
    OUTPUT_VARIABLE listed RESULT_VARIABLE status)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "${binary} --list failed (${status})")
  endif()
  string(REGEX MATCHALL "[^\n]+: test" tests "${listed}")
  list(TRANSFORM tests REPLACE ": test$" "")
  set(${out} "${tests}" PARENT_SCOPE)
endfunction()

if(mode STREQUAL "build")
  set(profile)
  set(packages)
  foreach(arg IN LISTS args)
    if(arg STREQUAL "--release")
      set(profile --release)
    else()
      list(APPEND packages -p "${arg}")
    endif()
  endforeach()
  # Cargo's messages are JSON on standard output, its progress and the
  # compilers' diagnostics go to standard error as usual.
  execute_process(COMMAND "${CARGO}" test --no-run --manifest-path "${MANIFEST}" ${profile} ${packages}
                          --message-format json-render-diagnostics
    OUTPUT_VARIABLE messages RESULT_VARIABLE status)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "cargo test --no-run failed (${status})")
  endif()
  # The test binaries: the artifacts with an executable built as tests (not
  # the programs that integration tests run).
  string(REGEX MATCHALL "[^\n]*\"executable\":\"[^\n]*" artifacts "${messages}")
  set(lines)
  foreach(artifact IN LISTS artifacts)
    string(JSON test GET "${artifact}" profile test)
    if(NOT test)
      continue()
    endif()
    string(JSON id GET "${artifact}" package_id)
    string(JSON manifest GET "${artifact}" manifest_path)
    string(JSON kind GET "${artifact}" target kind 0)
    string(JSON target GET "${artifact}" target name)
    string(JSON executable GET "${artifact}" executable)
    package_name("${id}" name)
    file(TO_CMAKE_PATH "${manifest}" manifest)
    get_filename_component(folder "${manifest}" DIRECTORY)
    file(TO_CMAKE_PATH "${executable}" executable)
    list(APPEND lines "${name}\t${folder}\t${kind} ${target}\t${executable}")
  endforeach()
  list(SORT lines)
  list(LENGTH lines count)
  list(JOIN lines "\n" text)
  file(WRITE "${LIST}" "${text}\n")
  message("${count} test binaries listed in ${LIST}")

elseif(mode STREQUAL "run")
  list(POP_FRONT args package)
  binaries("${package}" entries)
  set(failed)
  foreach(entry IN LISTS entries)
    string(REPLACE "|" ";" fields "${entry}")
    list(GET fields 0 folder)
    list(GET fields 1 target)
    list(GET fields 2 binary)
    message("${target}")
    execute_process(COMMAND "${binary}" --quiet ${args} WORKING_DIRECTORY "${folder}" RESULT_VARIABLE status)
    if(NOT status EQUAL 0)
      list(APPEND failed "${target} (${status})")
    endif()
  endforeach()
  if(failed)
    list(JOIN failed ", " failed)
    message(FATAL_ERROR "failed: ${failed}")
  endif()

elseif(mode STREQUAL "parts")
  list(POP_FRONT args package)
  set(filters "${args}")
  if(NOT filters)
    message(FATAL_ERROR "parts: no filters")
  endif()
  list(LENGTH filters parts)
  math(EXPR last_part "${parts} - 1")
  set(skips)
  foreach(i RANGE ${last_part})
    list(GET filters ${i} filter)
    list(APPEND skips --skip "${filter}")
    set(count_${i} 0)
  endforeach()
  set(count_rest 0)
  set(total 0)
  set(problems)
  binaries("${package}" entries)
  foreach(entry IN LISTS entries)
    string(REPLACE "|" ";" fields "${entry}")
    list(GET fields 0 folder)
    list(GET fields 1 target)
    list(GET fields 2 binary)
    list_tests("${binary}" "${folder}" all)
    set(listed)
    foreach(i RANGE ${last_part})
      list(GET filters ${i} filter)
      list_tests("${binary}" "${folder}" part "${filter}")
      list(LENGTH part n)
      math(EXPR count_${i} "${count_${i}} + ${n}")
      list(APPEND listed ${part})
    endforeach()
    list_tests("${binary}" "${folder}" rest ${skips})
    list(LENGTH rest n)
    math(EXPR count_rest "${count_rest} + ${n}")
    list(APPEND listed ${rest})
    list(LENGTH all n)
    math(EXPR total "${total} + ${n}")
    # Each test exactly once among the parts: the same lists when sorted,
    # else which tests are in no part or in several.
    list(SORT all)
    list(SORT listed)
    if(NOT all STREQUAL listed)
      foreach(test IN LISTS all)
        set(times 0)
        foreach(other IN LISTS listed)
          if(other STREQUAL test)
            math(EXPR times "${times} + 1")
          endif()
        endforeach()
        if(NOT times EQUAL 1)
          list(APPEND problems "${target}: ${test} is in ${times} parts")
        endif()
      endforeach()
    endif()
  endforeach()
  set(summary)
  foreach(i RANGE ${last_part})
    list(GET filters ${i} filter)
    list(APPEND summary "${filter} ${count_${i}}")
    if(count_${i} EQUAL 0)
      list(APPEND problems "no test matches ${filter}")
    endif()
  endforeach()
  list(APPEND summary "the rest ${count_rest}")
  list(JOIN summary ", " summary)
  message("${package}: ${total} tests; ${summary}")
  if(problems)
    list(JOIN problems "\n  " problems)
    message(FATAL_ERROR "${package}'s parts:\n  ${problems}")
  endif()

else()
  message(FATAL_ERROR "usage: cmake [-D...] -P cargo-tests.cmake -- build|run|parts ...")
endif()
